### ISSUE TITLE
Varying kinetic parameters when simulating true counts

### ISSUE THREAD

**Issue by JamesDanielOReilly** [YosefLab/SymSim#25]
Hello! I'm evaluating the effect of transcriptional bursting on heterogeneity in scRNA-seq datasets. As part of this, I'm using SymSim to simulate some data. I want to explicitly change the parameters used in the bursting model (k_on, k_off, s). 

I know that varying the number of EVFs will change the spread of the distributions for these kinetic parameters. See the images below which show the distributions of kinetic parameters for 10 EVFs and 1 EVF, respectively. However, the mode of these kinetic parameters stays the same, and I cannot figure out how to explicitly change these parameters so that I can explore the effects of these changes on heterogeneity.

![symsim-10evf](https://user-images.githubusercontent.com/44339381/109816255-d3494180-7c30-11eb-8e00-31e3e6247f24.png)
![symsim-1evf](https://user-images.githubusercontent.com/44339381/109816265-d5130500-7c30-11eb-943d-8649d66c9224.png)

Is it possible to either directly or indirectly change the mode of these parameters in SymSim? I noticed that the parameters are imputed from the Zeisel (2015) data set, and would like to instead supply my own. However, looking at the source code, this doesn't seem to be permitted. Could you suggest a way around this? Any advice is appreciated.

Cheers :)

**Comment by xiuweiz** [comment]
Hi, 

As you may have noticed, first the "pre-kinetic parameters" without using the distribution estimated from the Zeisel dataset are calculated from the EVF and gene effect parameters. However these "pre-kinetic parameters" do not follow any realistic distributions, so we "map" the "pre-kinetic parameters" to the distribution estimated from the Zeisel data. 

The real data distribution is included in the package and is loaded by `data(param_realdata.zeisel.imputed)`
If you simply would like to use your own distribution instead of the distribution from the Zeisel data you can replace `param_realdata.zeisel.imputed` with your own data. The variable in this data is `match_params`. The part of code which loads this data is from line 639 in 'simulation_functions.R'. Note that the format of `match_params` is as following:
```
> head(match_params)
           kon      koff          s
[1,] 1.1306431  3.235855 8163.38474
[2,] 0.2976902  1.068600 4080.94522
[3,] 0.4659142  6.900522  141.86383
[4,] 1.5373886 22.002473  533.43354
[5,] 0.1227865  7.031831   50.98967
[6,] 1.1432751  9.827708  820.51141
```
Where each column corresponds to all values from the distribution of that kinetic parameter. For each column we first perform log transformation and then estimate a density function to represent the distribution. 

Please let me know if there are further questions.

**Comment by JamesDanielOReilly** [comment]
Thanks for such a detailed response, that clears up almost all of my questions. As I want to simulate populations using kinetic parameters with different density functions, I will instead just generate the density distributions from scratch, instead of from a given dataset. I'll let you know if I have any more questions.
