### ISSUE TITLE
How to control variations in the input parameter

### ISSUE THREAD

**Issue by wangxlab** [YosefLab/SymSim#3]
Hi, 

I read SymSim vignettes and ran the code.  I have a question about input parameters to control variations.  In the line 47 of the vignettes, it says; 

The input parameters of the package allow users to control intrinsic variation, technical variation and biological variation in the data.

But I don't understand well how to control the intrinsic, technical, and biological variations. These variations are generated by the "True2ObservedCounts" function, not "SimulateTrueCounts" function, right? 

In the "True2ObservedCounts" function, the arguments that I can change are "alpha_mean", "allpha_sd", "depth_mean", and "depth_sd."   If I adjust these arguments, can I control the variations?   I like to make observed counts that have 1) intrinsic, 2) technical, or 3) biological variation, respectively.  Could you explain or show examples of arguments for me to make observed counts that have 1), 2), and 3) variations respectively?   

Thank you, 
Sanghoon

**Comment by xiuweiz** [comment]
Hi, Sanghoon,

Your true counts generated by SimulateTrueCounts already has intrinsic variation because we use the kinetic model to sample counts of molecules. To further increase this you can increase the parameter bimod in function SimulateTrueCounts which is defaulted to 0. In general you will have more genes expressed in bimodal distributions if this parameter increases (Figure 2d in the paper).

Technical variation is mainly controlled by alpha_mean, which represent the average mRNA capture efficiency. If you use nonUMI protocol, you will also have amplification bias as part of your technical variation, and that can be controlled through amp_bias_limit. depth_mean is the average sequencing depth. If you have very low sequencing depth, you will also have lower quality data and higher technical variation.

If you generate multiple populations, the biological variation has two parts: the within-population variation and the cross-population variation. If you generate only one population (1 cluster), you only have within-population variation. The within-population variation is controlled by parameter Sigma in function SimulateTrueCounts. The cross-population variation is controlled by the tree you give to argument "phyla" in function SimulateTrueCounts. If you increase branch length in the tree you will have larger cross-population variation.

**Comment by wangxlab** [comment]
Hi Xiuweiz, 

Thank you for your kind explanation. I can understand much better thanks to you.  1) Intrinsic variation is controlled by SimulateTrueCounts function, 2) Technical variation is controlled by 'alpha_mean' in UMI protocol, amp_bias_limt in nonUMI protocol,   or 'depth_mean' argument,  3) biological variation 'Sigma' or 'phyla' in function SimulateTrueCounts.   

Thank you!!
Sanghoon
